name: NuGet release
on:
  push:
    branches:
      - release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build solution
      run: dotnet build --output build -c Release
    - name: Publish NuGet package
      run: dotnet nuget push "build/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
      
